// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCJ2LClnvYUzKxXWKBKli0PHuWLfQbZvc',
    appId: '1:590730209574:web:e276241eed2008bfc5f9e7',
    messagingSenderId: '590730209574',
    projectId: 'coursedatabase-5a413',
    authDomain: 'coursedatabase-5a413.firebaseapp.com',
    storageBucket: 'coursedatabase-5a413.appspot.com',
    measurementId: 'G-G0EYYY2E9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOw_6CB2FYOcSdNKUg_1dj2ncOgbxJRwo',
    appId: '1:590730209574:android:5c7e65ec971a62a8c5f9e7',
    messagingSenderId: '590730209574',
    projectId: 'coursedatabase-5a413',
    storageBucket: 'coursedatabase-5a413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTKj0Wlco5NF16zmaj6W1sb94N74Qrphk',
    appId: '1:590730209574:ios:25912a7abc3ebba5c5f9e7',
    messagingSenderId: '590730209574',
    projectId: 'coursedatabase-5a413',
    storageBucket: 'coursedatabase-5a413.appspot.com',
    iosClientId: '590730209574-k8ilk42nrhfafc1jk2679mvegivlntma.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTKj0Wlco5NF16zmaj6W1sb94N74Qrphk',
    appId: '1:590730209574:ios:25912a7abc3ebba5c5f9e7',
    messagingSenderId: '590730209574',
    projectId: 'coursedatabase-5a413',
    storageBucket: 'coursedatabase-5a413.appspot.com',
    iosClientId: '590730209574-k8ilk42nrhfafc1jk2679mvegivlntma.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCJ2LClnvYUzKxXWKBKli0PHuWLfQbZvc',
    appId: '1:590730209574:web:21fa4d631d2de8e4c5f9e7',
    messagingSenderId: '590730209574',
    projectId: 'coursedatabase-5a413',
    authDomain: 'coursedatabase-5a413.firebaseapp.com',
    storageBucket: 'coursedatabase-5a413.appspot.com',
    measurementId: 'G-M2NVCK6Q0Z',
  );
}
